# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bcdice_info.proto for package 'bcdice_irc_proto'

require 'grpc'
require 'bcdice_info_pb'

module BcdiceIrcProto
  module BCDiceInfoService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bcdice_irc_proto.BCDiceInfoService'

      # Version はBCDice IRCおよび関連プログラムのバージョン情報を返す。
      rpc :Version, ::BcdiceIrcProto::VersionRequest, ::BcdiceIrcProto::VersionResponse
      # GetDiceBotList は、ダイスボットの一覧を返す。
      rpc :GetDiceBotList, ::BcdiceIrcProto::GetDiceBotListRequest, ::BcdiceIrcProto::GetDiceBotListResponse
      # Stop はサービスを停止する。
      rpc :Stop, ::BcdiceIrcProto::StopRequest, ::BcdiceIrcProto::StopResponse
    end

    Stub = Service.rpc_stub_class
  end
end
