# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bcdice_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("bcdice_info.proto", :syntax => :proto3) do
    add_message "bcdice_irc_proto.GetBCDiceVersionInfoRequest" do
    end
    add_message "bcdice_irc_proto.GetBCDiceVersionInfoResponse" do
      optional :bcdice_version, :string, 1
      optional :bcdice_irc_version, :string, 2
    end
    add_message "bcdice_irc_proto.GetDiceBotListRequest" do
    end
    add_message "bcdice_irc_proto.GetDiceBotListResponse" do
      repeated :dice_bots, :message, 1, "bcdice_irc_proto.DiceBot"
    end
    add_message "bcdice_irc_proto.DiceBot" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :help_message, :string, 3
    end
    add_message "bcdice_irc_proto.StopRequest" do
    end
    add_message "bcdice_irc_proto.StopResponse" do
      optional :ok, :bool, 1
    end
  end
end

module BcdiceIrcProto
  GetBCDiceVersionInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.GetBCDiceVersionInfoRequest").msgclass
  GetBCDiceVersionInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.GetBCDiceVersionInfoResponse").msgclass
  GetDiceBotListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.GetDiceBotListRequest").msgclass
  GetDiceBotListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.GetDiceBotListResponse").msgclass
  DiceBot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.DiceBot").msgclass
  StopRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.StopRequest").msgclass
  StopResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bcdice_irc_proto.StopResponse").msgclass
end
